version: "3.8"
services: 
    api: 
      image: ariel-monterroso/api-geo
      build:
        dockerfile: Dockerfile
        context: .
      depends_on:
        - postgres
        - redis
      ports:
        - "4000:3000"
    postgres:
      image: postgres:13
      environment: 
        - POSTGRES_DB=geo-db
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=12345678
      ports:
        - '5432:5432'

    pgadmin:
      image: 'dpage/pgadmin4'
      environment: 
          - PGADMIN_DEFAULT_EMAIL=bamonterroso@gmail.com
          - PGADMIN_DEFAULT_PASSWORD=12345678
      ports:
        - '5050:80'
    redis:
      image: redis:6.2
      environment:
          - ALLOW_EMPTY_PASSWORD=yes
          - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      ports:
          - '6379:6379'

      

